name: Laravel

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  laravel-tests:
    name: Laravel Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@main
        with:
          php-version: "8.3"

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install composer dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate key
        run: php artisan key:generate

      - name: Install npm dependencies and build
        run: |
          npm install
          npm run build

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: mysql
          DB_HOST: ${{ secrets.DB_TEST_HOST }}
          DB_DATABASE: ${{ secrets.DB_TEST_DATABASE }}
          DB_USERNAME: ${{ secrets.DB_TEST_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_TEST_PASSWORD }}
        run: php artisan test

  laravel-deploy:
    name: Deploy to Server
    needs: laravel-tests
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_PROD_HOST }}
          username: ${{ secrets.SERVER_PROD_USERNAME }}
          key: ${{ secrets.SERVER_PROD_SSH_KEY }}
          port: ${{ secrets.SERVER_PROD_PORT }}
          script: |
            cd ${{ secrets.SERVER_PROD_PATH }}
            git pull origin main
            composer install --no-dev
            npm install --production
            php artisan migrate
            php artisan optimize
            npm run build
